// Dataset d'emojis pour EmojiPicker — caractères Unicode natifs, aucune
// dépendance npm, aucun asset. Mots-clés en français pour la recherche.
export const EMOJI_CATEGORIES = [
  {
    id: "smileys",
    label: "Smileys",
    icon: "😀",
    emojis: [
      { e: "😀", k: ["content", "sourire", "heureux"] },
      { e: "😃", k: ["content", "joie"] },
      { e: "😄", k: ["content", "rire"] },
      { e: "😁", k: ["sourire", "dents"] },
      { e: "😆", k: ["rire", "content"] },
      { e: "😅", k: ["rire", "gêné", "sueur"] },
      { e: "🤣", k: ["mort de rire", "hilare"] },
      { e: "😂", k: ["rire", "larmes"] },
      { e: "🙂", k: ["sourire", "léger"] },
      { e: "🙃", k: ["envers", "ironie"] },
      { e: "😉", k: ["clin d'oeil", "complice"] },
      { e: "😊", k: ["content", "timide"] },
      { e: "😇", k: ["ange", "innocent"] },
      { e: "🥰", k: ["amour", "coeurs"] },
      { e: "😍", k: ["amour", "yeux coeur"] },
      { e: "🤩", k: ["étoiles", "impressionné"] },
      { e: "😘", k: ["bisou", "amour"] },
      { e: "😗", k: ["bisou"] },
      { e: "😋", k: ["gourmand", "miam"] },
      { e: "😛", k: ["langue", "taquin"] },
      { e: "😜", k: ["clin d'oeil", "langue"] },
      { e: "🤪", k: ["fou", "dingue"] },
      { e: "🤔", k: ["réflexion", "penser"] },
      { e: "🤨", k: ["sceptique", "sourcil"] },
      { e: "😐", k: ["neutre"] },
      { e: "😑", k: ["blasé", "neutre"] },
      { e: "😶", k: ["silence", "sans bouche"] },
      { e: "🙄", k: ["yeux au ciel", "exaspéré"] },
      { e: "😏", k: ["sourire narquois"] },
      { e: "😴", k: ["dormir", "fatigue"] },
      { e: "😪", k: ["fatigue", "somnolent"] },
      { e: "🥱", k: ["baillement", "fatigue"] },
      { e: "😌", k: ["soulagé", "paisible"] },
      { e: "😢", k: ["triste", "pleure"] },
      { e: "😭", k: ["pleure", "larmes"] },
      { e: "😤", k: ["frustré", "colère"] },
      { e: "😠", k: ["colère", "fâché"] },
      { e: "😡", k: ["colère", "furieux"] },
      { e: "🥵", k: ["chaud"] },
      { e: "🥶", k: ["froid"] },
      { e: "😱", k: ["choqué", "peur"] },
      { e: "😨", k: ["peur"] },
      { e: "😰", k: ["anxieux", "stress"] },
      { e: "🥺", k: ["yeux suppliants", "attendrissant"] },
      { e: "🤗", k: ["câlin", "accolade"] },
      { e: "🤭", k: ["gêné", "surpris"] },
      { e: "🤫", k: ["chut", "silence"] },
      { e: "🤯", k: ["explosé", "choqué"] },
      { e: "😷", k: ["malade", "masque"] },
      { e: "🤒", k: ["malade", "fièvre"] },
      { e: "😎", k: ["cool", "lunettes"] },
      { e: "🥳", k: ["fête", "célébration"] },
    ],
  },
  {
    id: "people",
    label: "Personnes",
    icon: "🙋",
    emojis: [
      { e: "👋", k: ["salut", "au revoir"] },
      { e: "🤚", k: ["main levée"] },
      { e: "✋", k: ["stop", "main"] },
      { e: "🖖", k: ["salut vulcain"] },
      { e: "👌", k: ["ok", "parfait"] },
      { e: "🤌", k: ["pincé", "quoi"] },
      { e: "✌️", k: ["victoire", "paix"] },
      { e: "🤞", k: ["doigts croisés", "chance"] },
      { e: "🤝", k: ["poignée de main", "accord"] },
      { e: "👍", k: ["pouce levé", "ok", "bien"] },
      { e: "👎", k: ["pouce baissé", "mauvais"] },
      { e: "👏", k: ["applaudir", "bravo"] },
      { e: "🙌", k: ["mains levées", "célébration"] },
      { e: "🙏", k: ["merci", "prière", "svp"] },
      { e: "💪", k: ["force", "muscle"] },
      { e: "🫶", k: ["coeur mains", "amour"] },
      { e: "👀", k: ["yeux", "regarder"] },
      { e: "🧑", k: ["personne"] },
      { e: "👨", k: ["homme"] },
      { e: "👩", k: ["femme"] },
      { e: "🧓", k: ["personne âgée"] },
      { e: "👶", k: ["bébé"] },
      { e: "🧑‍🦱", k: ["personne", "cheveux bouclés"] },
      { e: "🧑‍🦰", k: ["personne", "roux"] },
      { e: "🧑‍🎓", k: ["étudiant", "diplôme"] },
      { e: "🧑‍💻", k: ["informaticien", "ordinateur"] },
      { e: "🧑‍🍳", k: ["cuisinier", "chef"] },
      { e: "🧑‍🚀", k: ["astronaute"] },
      { e: "💑", k: ["couple", "amour"] },
      { e: "👪", k: ["famille"] },
      { e: "💃", k: ["danse", "femme"] },
      { e: "🕺", k: ["danse", "homme"] },
    ],
  },
  {
    id: "animals",
    label: "Animaux",
    icon: "🐶",
    emojis: [
      { e: "🐶", k: ["chien"] },
      { e: "🐱", k: ["chat"] },
      { e: "🐭", k: ["souris"] },
      { e: "🐹", k: ["hamster"] },
      { e: "🐰", k: ["lapin"] },
      { e: "🦊", k: ["renard"] },
      { e: "🐻", k: ["ours"] },
      { e: "🐼", k: ["panda"] },
      { e: "🐨", k: ["koala"] },
      { e: "🐯", k: ["tigre"] },
      { e: "🦁", k: ["lion"] },
      { e: "🐮", k: ["vache"] },
      { e: "🐷", k: ["cochon"] },
      { e: "🐸", k: ["grenouille"] },
      { e: "🐵", k: ["singe"] },
      { e: "🐔", k: ["poule"] },
      { e: "🐧", k: ["pingouin"] },
      { e: "🐦", k: ["oiseau"] },
      { e: "🦆", k: ["canard"] },
      { e: "🦅", k: ["aigle"] },
      { e: "🦉", k: ["hibou"] },
      { e: "🦋", k: ["papillon"] },
      { e: "🐝", k: ["abeille"] },
      { e: "🐢", k: ["tortue"] },
      { e: "🐍", k: ["serpent"] },
      { e: "🦎", k: ["lézard"] },
      { e: "🐳", k: ["baleine"] },
      { e: "🐬", k: ["dauphin"] },
      { e: "🐠", k: ["poisson"] },
      { e: "🦒", k: ["girafe", "baobab"] },
      { e: "🐘", k: ["éléphant"] },
      { e: "🦓", k: ["zèbre"] },
      { e: "🦍", k: ["gorille"] },
      { e: "🐴", k: ["cheval"] },
      { e: "🐑", k: ["mouton"] },
    ],
  },
  {
    id: "food",
    label: "Nourriture",
    icon: "🍕",
    emojis: [
      { e: "🍎", k: ["pomme"] },
      { e: "🍌", k: ["banane"] },
      { e: "🍇", k: ["raisin"] },
      { e: "🍓", k: ["fraise"] },
      { e: "🍍", k: ["ananas"] },
      { e: "🥭", k: ["mangue"] },
      { e: "🍑", k: ["pêche"] },
      { e: "🥑", k: ["avocat"] },
      { e: "🌽", k: ["maïs"] },
      { e: "🥕", k: ["carotte"] },
      { e: "🍕", k: ["pizza"] },
      { e: "🍔", k: ["burger"] },
      { e: "🍟", k: ["frites"] },
      { e: "🌭", k: ["hot dog"] },
      { e: "🥪", k: ["sandwich"] },
      { e: "🌮", k: ["taco"] },
      { e: "🍝", k: ["pâtes"] },
      { e: "🍜", k: ["nouilles", "soupe"] },
      { e: "🍲", k: ["ragoût", "mafé"] },
      { e: "🍚", k: ["riz"] },
      { e: "🍗", k: ["poulet"] },
      { e: "🥘", k: ["plat", "poêle"] },
      { e: "🍤", k: ["crevette"] },
      { e: "🍦", k: ["glace"] },
      { e: "🍩", k: ["donut"] },
      { e: "🍪", k: ["biscuit"] },
      { e: "🎂", k: ["gâteau", "anniversaire"] },
      { e: "🍫", k: ["chocolat"] },
      { e: "☕", k: ["café"] },
      { e: "🍵", k: ["thé"] },
      { e: "🧃", k: ["jus"] },
      { e: "🥤", k: ["boisson"] },
      { e: "🍷", k: ["vin"] },
      { e: "🍺", k: ["bière"] },
    ],
  },
  {
    id: "travel",
    label: "Voyages",
    icon: "✈️",
    emojis: [
      { e: "✈️", k: ["avion"] },
      { e: "🚗", k: ["voiture"] },
      { e: "🚕", k: ["taxi"] },
      { e: "🚌", k: ["bus"] },
      { e: "🚆", k: ["train"] },
      { e: "🚲", k: ["vélo"] },
      { e: "🛵", k: ["scooter"] },
      { e: "🚀", k: ["fusée"] },
      { e: "⛵", k: ["voilier", "bateau"] },
      { e: "🚢", k: ["bateau"] },
      { e: "🗺️", k: ["carte", "voyage"] },
      { e: "🧳", k: ["valise", "bagage"] },
      { e: "🗽", k: ["statue liberté", "usa"] },
      { e: "🏔️", k: ["montagne"] },
      { e: "🏖️", k: ["plage"] },
      { e: "🏙️", k: ["ville"] },
      { e: "🌆", k: ["ville", "coucher soleil"] },
      { e: "🏠", k: ["maison"] },
      { e: "🏢", k: ["immeuble", "bureau"] },
      { e: "🕌", k: ["mosquée"] },
      { e: "⛪", k: ["église"] },
      { e: "🌍", k: ["monde", "afrique", "europe"] },
      { e: "🌎", k: ["monde", "amériques"] },
      { e: "🗼", k: ["tour"] },
      { e: "🎡", k: ["grande roue"] },
      { e: "🚦", k: ["feu circulation"] },
      { e: "🧭", k: ["boussole"] },
      { e: "🌤️", k: ["soleil", "nuage"] },
      { e: "❄️", k: ["neige", "froid"] },
    ],
  },
  {
    id: "activities",
    label: "Activités",
    icon: "⚽",
    emojis: [
      { e: "⚽", k: ["football", "ballon"] },
      { e: "🏀", k: ["basketball"] },
      { e: "🏈", k: ["football américain"] },
      { e: "🎾", k: ["tennis"] },
      { e: "🏐", k: ["volleyball"] },
      { e: "🏓", k: ["ping pong"] },
      { e: "🥊", k: ["boxe"] },
      { e: "🏃", k: ["courir"] },
      { e: "🚴", k: ["vélo", "cyclisme"] },
      { e: "🏋️", k: ["musculation", "gym"] },
      { e: "🧘", k: ["yoga", "méditation"] },
      { e: "🏊", k: ["natation"] },
      { e: "🎣", k: ["pêche"] },
      { e: "🎮", k: ["jeu vidéo", "manette"] },
      { e: "🎲", k: ["dé", "jeu"] },
      { e: "🎯", k: ["cible", "précision"] },
      { e: "🎨", k: ["peinture", "art"] },
      { e: "🎬", k: ["cinéma", "film"] },
      { e: "🎤", k: ["micro", "chant"] },
      { e: "🎧", k: ["écouteurs", "musique"] },
      { e: "🎸", k: ["guitare"] },
      { e: "🎹", k: ["piano"] },
      { e: "📚", k: ["livres", "lecture"] },
      { e: "✏️", k: ["crayon", "écrire"] },
      { e: "🎉", k: ["fête", "célébration"] },
      { e: "🎊", k: ["confettis", "fête"] },
      { e: "🥂", k: ["trinquer", "célébration"] },
      { e: "🏆", k: ["trophée", "victoire"] },
    ],
  },
  {
    id: "objects",
    label: "Objets",
    icon: "💡",
    emojis: [
      { e: "📱", k: ["téléphone", "portable"] },
      { e: "💻", k: ["ordinateur", "laptop"] },
      { e: "⌚", k: ["montre"] },
      { e: "📷", k: ["appareil photo"] },
      { e: "💡", k: ["ampoule", "idée"] },
      { e: "🔋", k: ["batterie"] },
      { e: "🔑", k: ["clé"] },
      { e: "🔒", k: ["cadenas", "sécurité"] },
      { e: "📌", k: ["épingle"] },
      { e: "📎", k: ["trombone", "pièce jointe"] },
      { e: "✉️", k: ["enveloppe", "email"] },
      { e: "📩", k: ["message reçu"] },
      { e: "💰", k: ["argent"] },
      { e: "💳", k: ["carte bancaire"] },
      { e: "🎁", k: ["cadeau"] },
      { e: "🎈", k: ["ballon"] },
      { e: "💐", k: ["bouquet", "fleurs"] },
      { e: "🌹", k: ["rose"] },
      { e: "🌸", k: ["fleur"] },
      { e: "🕯️", k: ["bougie"] },
      { e: "⏰", k: ["réveil", "alarme"] },
      { e: "🕐", k: ["horloge", "heure"] },
      { e: "📖", k: ["livre ouvert"] },
      { e: "📝", k: ["note", "écrire"] },
      { e: "💼", k: ["mallette", "travail"] },
      { e: "🛒", k: ["panier", "courses"] },
      { e: "🧳", k: ["valise"] },
    ],
  },
  {
    id: "symbols",
    label: "Symboles",
    icon: "❤️",
    emojis: [
      { e: "❤️", k: ["coeur", "amour"] },
      { e: "🧡", k: ["coeur orange"] },
      { e: "💛", k: ["coeur jaune"] },
      { e: "💚", k: ["coeur vert"] },
      { e: "💙", k: ["coeur bleu"] },
      { e: "💜", k: ["coeur violet"] },
      { e: "🖤", k: ["coeur noir"] },
      { e: "🤍", k: ["coeur blanc"] },
      { e: "💔", k: ["coeur brisé"] },
      { e: "💕", k: ["coeurs", "amour"] },
      { e: "💖", k: ["coeur scintillant"] },
      { e: "💗", k: ["coeur grandissant"] },
      { e: "💯", k: ["cent pourcent", "parfait"] },
      { e: "✅", k: ["coché", "validé"] },
      { e: "❌", k: ["croix", "erreur"] },
      { e: "❓", k: ["question"] },
      { e: "❗", k: ["exclamation", "important"] },
      { e: "⭐", k: ["étoile"] },
      { e: "✨", k: ["étincelles", "brillant"] },
      { e: "🔥", k: ["feu", "cool"] },
      { e: "⚡", k: ["éclair", "rapide"] },
      { e: "🌈", k: ["arc-en-ciel"] },
      { e: "☀️", k: ["soleil"] },
      { e: "🌙", k: ["lune"] },
      { e: "⚠️", k: ["attention", "danger"] },
      { e: "♻️", k: ["recyclage"] },
      { e: "🔞", k: ["18 ans", "interdit"] },
      { e: "🆗", k: ["ok"] },
      { e: "🔴", k: ["cercle rouge"] },
      { e: "🟢", k: ["cercle vert"] },
    ],
  },
  {
    id: "flags",
    label: "Drapeaux",
    icon: "🏳️",
    emojis: [
      { e: "🇨🇦", k: ["canada"] },
      { e: "🇫🇷", k: ["france"] },
      { e: "🇧🇪", k: ["belgique"] },
      { e: "🇨🇭", k: ["suisse"] },
      { e: "🇺🇸", k: ["états-unis", "usa"] },
      { e: "🇬🇧", k: ["royaume-uni", "angleterre"] },
      { e: "🇸🇳", k: ["sénégal"] },
      { e: "🇨🇮", k: ["côte d'ivoire"] },
      { e: "🇨🇲", k: ["cameroun"] },
      { e: "🇨🇩", k: ["congo", "rdc"] },
      { e: "🇬🇦", k: ["gabon"] },
      { e: "🇲🇱", k: ["mali"] },
      { e: "🇧🇯", k: ["bénin"] },
      { e: "🇹🇬", k: ["togo"] },
      { e: "🇧🇫", k: ["burkina faso"] },
      { e: "🇬🇳", k: ["guinée"] },
      { e: "🇲🇦", k: ["maroc"] },
      { e: "🇩🇿", k: ["algérie"] },
      { e: "🇹🇳", k: ["tunisie"] },
      { e: "🇭🇹", k: ["haïti"] },
      { e: "🏳️", k: ["drapeau blanc"] },
      { e: "🏁", k: ["damier", "arrivée"] },
    ],
  },
];

export function searchEmojis(query) {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const results = [];
  for (const cat of EMOJI_CATEGORIES) {
    for (const item of cat.emojis) {
      if (item.k.some((kw) => kw.includes(q))) results.push(item);
    }
  }
  return results;
}
